### ISSUE TITLE
Will this be updated to mc version 1.16.5

### ISSUE THREAD

**Issue by disduke** [JDar2K/Fabric-Clientside-Pack#2]
Will the mod pack be updated to 1.16.5 any time soon?

**Comment by jSQrD-dev** [comment]
I'm working on one now I was waiting for 1.16 to stop updating

**Comment by disduke** [comment]
oh ok, thanks btw love the work, finding client-side mods are hard.

**Comment by jSQrD-dev** [comment]
Check out this modpack in the meantime https://www.curseforge.com/minecraft/modpacks/fabulously-optimized it's mostly performance, but it is now the base of my new version.
